name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11.4'

      - name: Setup Python Virtual Environment
        run: python -m venv venv

      - name: Install Dependencies
        run: venv/bin/pip install -r requirements.txt

      - name: Run Tests
        run: ./run_tests.sh
